---
title: "Class 6 R Functions"
author: "Tiffany"
date: "10/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This is H1
This is my work from class6 in **BIMM143**.

```{r}
# this is to deom a code chunk
plot(1:10)
```


## Practive reading files (again...)

```{r}
read.table("test1.txt", sep=",", header=TRUE)
```

```{r}
read.table("test2.txt", sep="$", header=TRUE)
```

```{r}
read.table("test3.txt")
```

```{r}
add <- function(x, y=1) {
 # Sum the input x and y
 x + y
}
```
#the y arguement is optional


```{r}
add(1)
add(5,5) #here ,5 overrides the y arguement
#add(5,barry)
```

```{r}
add(c(1,2,3))
add( c(1, 2, 3), 4 )
```

A new function to re-scale data
```{r}
rescale <- function(x) {
 rng <-range(x)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(1:10)
```


test some
```{r}
rescale(c(1,2,NA,3,10))
```


```{r}
x<-c(1,2,NA,3,10)
rng<-range(x, na.rm = TRUE)
rng
```


```{r}
rescale2 <- function(x) {
 rng <-range(x, na.rm = TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}
```


```{r}
rescale2(c(1,2,NA,3,10))
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 rng <-range(x, na.rm=na.rm)
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
 }
 print("I can see it in ...")
 return(answer)
}
```

```{r}
rescale3(1:10, plot = TRUE)
```


```{r}
rescale4 <- function(x, na.rm=TRUE, plot=FALSE) {
 rng <-range(x, na.rm=na.rm)
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 return(answer)
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
 }
 print("I can see it in ...")
 #return(answer)
}
```


```{r}
rescale4(1:10)
```


#section 2 of the hands-on sheet

Install the **bio3d** package for sequence and structure analysis
```{r}
#install.packages(“bio3d”)
```

```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```
``
`
```{r}
pdb<- read.pdb("4AKE")
print(pdb)
```




